workflows:
  unsigned-ipa:
    name: Build unsigned iOS .ipa (device) - safe KMP copy + pod install
    max_build_duration: 60
    environment:
      vars:
        XCODE_PROJECT: "iosApp/iosApp.xcodeproj"
        XCODE_SCHEME: "iosApp"
        XCODE_DESTINATION: "generic/platform=iOS"
        GRADLE_TASK: "composeApp:embedAndSignAppleFrameworkForXcode"
    scripts:
      - name: Run Gradle task to prepare iOS frameworks
        script: |
          echo "=== Running Gradle task: $GRADLE_TASK ==="
          chmod +x ./gradlew
          ./gradlew $GRADLE_TASK --no-daemon
      - name: Collect and copy any produced frameworks to iosApp/Frameworks
        script: |
          echo "=== Searching for .framework/.xcframework outputs ==="
          # find frameworks produced by Gradle and copy them into iosApp/Frameworks so Xcode can link them
          OUT_DIRS=$(find . -type d -name "*.framework" -o -name "*.xcframework" -print0 | xargs -0 -n1 dirname 2>/dev/null | sort -u || true)
          echo "Framework parent dirs found:"
          echo "$OUT_DIRS"
          mkdir -p iosApp/Frameworks
          # Find and copy individual frameworks / xcframeworks
          find . -type d \( -name "*.framework" -o -name "*.xcframework" \) -print0 | while IFS= read -r -d '' fw; do
            echo "Copying $fw -> iosApp/Frameworks/"
            cp -R "$fw" iosApp/Frameworks/ || true
          done
          echo "Copied frameworks to iosApp/Frameworks (if any were found)."
          echo "Listing iosApp/Frameworks:"
          ls -la iosApp/Frameworks || true
      - name: CocoaPods install (if Podfile present)
        script: |
          if [ -f "iosApp/Podfile" ]; then
            echo "Podfile found — running pod install"
            cd iosApp || exit 1
            if ! command -v pod >/dev/null 2>&1; then
              echo "Installing CocoaPods via gem"
              sudo gem install cocoapods --no-document || true
            fi
            pod install --repo-update || pod install || true
            cd -
          else
            echo "No Podfile found in iosApp/ — skipping pod install"
          fi
      - name: Build unsigned app for device (no signing)
        script: |
          set -e
          echo "=== Building unsigned .app (device) ==="
          if [ -n "$XCODE_WORKSPACE" ] && [ -f "$XCODE_WORKSPACE" ]; then
            xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" -configuration Release -destination "$XCODE_DESTINATION" clean build \
              CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO BUILD_DIR="$CM_BUILD_DIR/build"
          elif [ -n "$XCODE_PROJECT" ] && [ -f "$XCODE_PROJECT" ]; then
            xcodebuild -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME" -configuration Release -destination "$XCODE_DESTINATION" clean build \
              CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO BUILD_DIR="$CM_BUILD_DIR/build"
          else
            echo "ERROR: Neither workspace nor project found at the configured paths."
            ls -la || true
            exit 1
          fi
          echo "Build products (top-level of build dir):"
          find "$CM_BUILD_DIR/build" -maxdepth 6 -print || true
      - name: Package unsigned .app into unsigned .ipa
        script: |
          set -e
          APP_PATH=$(find "$CM_BUILD_DIR/build" -type d -name "*.app" | head -n 1)
          if [ -z "$APP_PATH" ]; then
            echo "ERROR: .app not found in build dir ($CM_BUILD_DIR/build)"
            exit 1
          fi
          echo "Found app at: $APP_PATH"
          mkdir -p "$CM_BUILD_DIR/ipas"
          rm -rf Payload
          mkdir Payload
          cp -R "$APP_PATH" Payload/
          /usr/bin/zip -r "$CM_BUILD_DIR/ipas/${XCODE_SCHEME}-unsigned.ipa" Payload > /dev/null
          echo "Unsigned IPA created: $CM_BUILD_DIR/ipas/${XCODE_SCHEME}-unsigned.ipa"
          rm -rf Payload
    artifacts:
      - $CM_BUILD_DIR/ipas/*.ipa
      - $CM_BUILD_DIR/build/**/*
      - iosApp/Frameworks/**
