workflows:
  unsigned-ipa:
    name: Build unsigned iOS .ipa (device) - detect Gradle tasks
    max_build_duration: 40
    environment:
      vars:
        XCODE_PROJECT: "iosApp/iosApp.xcodeproj"
        XCODE_SCHEME: "iosApp"
        XCODE_DESTINATION: "generic/platform=iOS"
        LIST_GRADLE_TASKS: "true"
    scripts:
      - name: List Gradle tasks (produce gradle_tasks.txt)
        script: |
          if [ "$LIST_GRADLE_TASKS" = "true" ]; then
            echo "=== Listing all Gradle tasks (this can be large) ==="
            chmod +x ./gradlew
            ./gradlew tasks --all > "$CM_BUILD_DIR/gradle_tasks.txt" || true
            echo "Saved gradle task list to $CM_BUILD_DIR/gradle_tasks.txt"
          else
            echo "Skipping Gradle task listing (LIST_GRADLE_TASKS != true)"
          fi
      - name: (optional) Run Gradle task if configured and present
        script: |
          if [ -n "$GRADLE_TASK" ]; then
            echo "GRADLE_TASK is set to: $GRADLE_TASK — attempting to run it"
            chmod +x ./gradlew
            ./gradlew $GRADLE_TASK --no-daemon
          else
            echo "GRADLE_TASK not set — skipping Gradle step"
          fi
      - name: Build unsigned app for device
        script: |
          set -e
          echo "=== Building unsigned .app (device) ==="
          if [ -n "$XCODE_WORKSPACE" ] && [ -f "$XCODE_WORKSPACE" ]; then
            xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" -configuration Release -destination "$XCODE_DESTINATION" clean build \
              CODE_SIGN_IDENTITY="" \
              CODE_SIGNING_REQUIRED=NO \
              CODE_SIGNING_ALLOWED=NO \
              BUILD_DIR="$CM_BUILD_DIR/build"
          elif [ -n "$XCODE_PROJECT" ] && [ -f "$XCODE_PROJECT" ]; then
            xcodebuild -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME" -configuration Release -destination "$XCODE_DESTINATION" clean build \
              CODE_SIGN_IDENTITY="" \
              CODE_SIGNING_REQUIRED=NO \
              CODE_SIGNING_ALLOWED=NO \
              BUILD_DIR="$CM_BUILD_DIR/build"
          else
            echo "ERROR: Neither workspace nor project found at the configured paths."
            ls -la || true
            exit 1
          fi
          echo "Build products (top-level of build dir):"
          find "$CM_BUILD_DIR/build" -maxdepth 4 -print || true
      - name: Package unsigned .app into unsigned .ipa
        script: |
          set -e
          APP_PATH=$(find "$CM_BUILD_DIR/build" -type d -name "*.app" | head -n 1)
          if [ -z "$APP_PATH" ]; then
            echo "ERROR: .app not found in build dir ($CM_BUILD_DIR/build)"
            exit 1
          fi
          echo "Found app at: $APP_PATH"
          mkdir -p "$CM_BUILD_DIR/ipas"
          rm -rf Payload
          mkdir Payload
          cp -R "$APP_PATH" Payload/
          /usr/bin/zip -r "$CM_BUILD_DIR/ipas/${XCODE_SCHEME}-unsigned.ipa" Payload > /dev/null
          echo "Unsigned IPA created: $CM_BUILD_DIR/ipas/${XCODE_SCHEME}-unsigned.ipa"
          rm -rf Payload
      - name: List artifacts (for debug)
        script: |
          echo "Artifacts produced:"
          find $CM_BUILD_DIR -maxdepth 4 -type f -name "*.ipa" -print || true
          if [ -f "$CM_BUILD_DIR/gradle_tasks.txt" ]; then
            echo "Gradle task list available at $CM_BUILD_DIR/gradle_tasks.txt"
          fi
    artifacts:
      - $CM_BUILD_DIR/ipas/*.ipa
      - $CM_BUILD_DIR/build/**/*
      - $CM_BUILD_DIR/gradle_tasks.txt
